cmapi/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^', include('consent.urls', namespace='consent')),
    re_path(r'^', include('conformance.urls', namespace='conformance')),
]

conformance/urls.py
from django.urls import re_path

from . import views

app_name = 'conformance'

urlpatterns = [
    re_path(r'^manageresources/$', views.upload_resource, name='manageresources'),
    re_path(r'^capabilitystatement/$', views.get_capability_statement, name='capabilitystatement'),
]

consent/urls.py
from django.urls import re_path

from . import views

app_name = 'consent'

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^consentapproval/$', views.consentapproval, name='consentapproval'),
    re_path(r'^displaydata/(?P<requestid>[0-9]+)/$', views.displaydata, name='displaydata'),
]

consent/models.py
from django.db import models


class ConsentRequest(models.Model):
    patientid = models.CharField(max_length=50, null=False)
    requestedrole = models.CharField(max_length=30, null=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=25, default='Pending')
    consentid = models.UUIDField(null=True)

    def __str__(self):
        return self.patientid + ' (' + self.requestedrole + ')'

consent/forms.py
from django import forms

from .models import ConsentRequest


class ConsentRequestForm(forms.ModelForm):

    class Meta:
        model = ConsentRequest
        fields = ['patientid', 'requestedrole']

conformance/views.py
import json

from django.shortcuts import render

from .utils import create_data, get_fhir_metadata


def upload_resource(request):
    if request.method == 'POST':
        json_file = request.FILES['json_file']
        if not json_file:
            return render(request, 'manageresources.html', {'message': 'Please upload valid json file.'})

        try:
            data = json.load(json_file)
        except Exception as exc:
            message = str(exc)
        else:
            resp = create_data(data)
            if resp.get('error'):
                message = resp.get('message', 'File upload not succeeded.')
            else:
                message = resp.get('message', 'Success')
        return render(request, 'manageresources.html', {'message': message})
    else:
        return render(request, 'manageresources.html')


def get_capability_statement(request):
    resp = get_fhir_metadata()
    if resp.get('error'):
        message = resp.get('message', 'Error fetching capability statement')
        return render(request, 'capabilitystatement.html', {'message': message})
    return render(request, 'capabilitystatement.html', {'requests': json.dumps(resp.get('data', {}))})

consent/views.py
import json

from django.http import JsonResponse
from django.shortcuts import render

from .models import ConsentRequest
from .utils import create_consent, get_consent, get_data


def index(request):
    if request.method != "POST":
        message = " "
        return render(request, 'index.html', {'message': message})

    userid = request.POST.get("userid")
    role = request.POST.get("roles")

    if not userid or not role:
        message = "User id is not provided"
        return render(request, 'index.html', {'message': message})

    if 'checkConsent' in request.POST:
        cr = ConsentRequest.objects.filter(patientid=userid, requestedrole=role, status__in=['Pending', 'Approved'])
        if not cr:
            nomessage = "No records of user consent for the requested role. \nTo request for user consent click the 'Request Consent' button above"
            return render(request, 'index.html', {'nomessage': nomessage, 'userid': userid, 'roles': role})

        if not cr[0].consentid:
            return render(request, 'index.html', {'requests': cr, 'userid': userid, 'roles': role})

        resp = get_consent(cr[0].consentid)
        if resp.get('error'):
            nomessage = resp.get('message', 'Something went wrong during checking consent')
            if nomessage in ['Consent Expired', 'Consent not allowed without any expiry']:
                cr.update(status='Expired')
            return render(request, 'index.html', {'nomessage': nomessage, 'userid': userid, 'roles': role})

        expireTime = resp.get('data', {}).get('expireTime')
        return render(request, 'index.html', {'requests': cr, 'expireTime': expireTime})
    elif 'requestConsent' in request.POST:
        pending_requests = ConsentRequest.objects.filter(patientid=userid, requestedrole=role, status="Pending")
        if pending_requests:
            message = "There is a pending request for user consent with same role."
            return render(request, 'index.html', {'message': message})

        cr = ConsentRequest.objects.create(patientid=userid, requestedrole=role, status='Pending')
        return render(request, 'index.html', {'requests': [cr]})


def consentapproval(request):
    if request.method == 'POST' and 'approve' in request.POST:
        requestid = request.POST.get('approve')
        ttl = request.POST.get(requestid+'_ttl')
        cr = ConsentRequest.objects.filter(id=requestid)
        resp = create_consent(cr[0].patientid, cr[0].requestedrole, ttl)
        if resp.get('error'):
            message = resp.get('message', 'Something went wrong during consent creation, please try again')
            return render(request, 'consentapproval.html', {'message': message, 'requests': cr})

        cr.update(consentid=resp.get('data', {}).get('consent_id', ''), status='Approved')
    elif request.method == 'POST' and 'reject' in request.POST:
        requestid = request.POST.get('reject')
        ConsentRequest.objects.filter(id=requestid).update(status='Rejected')

        cr = ConsentRequest.objects.filter(status__in=['Pending']).order_by('-timestamp')
        if cr:
            return render(request, 'consentapproval.html', {'requests': cr})

        message = "No records found"
        return render(request, 'consentapproval.html', {'message': message})

    cr = ConsentRequest.objects.filter(status__in=['Pending']).order_by('-timestamp')
    if cr:
        return render(request, 'consentapproval.html', {'requests': cr})

    message = "No records found"
    return render(request, 'consentapproval.html', {'message': message})


def displaydata(request, requestid):
    cr = ConsentRequest.objects.filter(id=requestid)
    resp = get_data(cr[0].patientid, cr[0].requestedrole, cr[0].consentid)
    if resp.get('error'):
        if resp.get('message', '') == 'Consent Expired':
            cr.update(status='Expired')
        return JsonResponse(resp, safe=False)
    return JsonResponse(resp, safe=False)

conformance/templates/capabilitystatement.html
{% extends 'base.html' %}

{% block capabilitystatement_active %}active{% endblock %}

{% block body %}
  <script>
    $(function() {
      var djangoData = $('#my-data').data()['statement'];
      document.getElementById("data-container").innerHTML = JSON.stringify(djangoData, null, 4);
    });
  </script>

  <div class="page-header">
    <h1>Capability/Conformance Statement</h1>
  </div>

  <div class="row">
    <div class="alert alert-warning" role="alert">
      <strong>Capabilities or conformance statement for a FHIR store</strong>
    </div>
  </div>

  {% if message %}
    <h4> {{ message }} </h4>
  {% endif %}

  <div class="row">
    <div class="col-sm-12">
      <div class="row">
        <div class="col-sm-12">
          <ul class="nav nav-pills" style="margin-bottom: 10px;">
            <meta id="my-data" data-statement="{{requests}}">
            <div style="width: 100%; height: 450px; overflow: scroll;">
              <pre id="data-container"></pre>
            </div>
          </ul>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

consent/templates/capabilitystatement.html
{% extends 'base.html' %}

{% block body %}
  <script>
    $(function() {
      var djangoData = $('#my-data').data()['statement'];
      document.getElementById("data-container").innerHTML = JSON.stringify(djangoData, null, 4);
    });
  </script>

  <nav class="navbar navbar-default">
    <ul class="nav navbar-nav">
      <li><a href="{% url 'consent:index'%}">Home</a></li>
      <li><a href="{% url 'consent:consentapproval'%}">Consent Approval</a></li>
      <li><a href="{% url 'consent:manageresources'%}">Manage Resources</a></li>
      <li class="active"><a href="{% url 'consent:capabilitystatement'%}">Capability Statement</a></li>
    </ul>
  </nav>

  <div class="page-header">
    <h1>Capability/Conformance Statement</h1>
  </div>

  <div class="row">
    <div class="alert alert-warning" role="alert">
      <strong>Capabilities or conformance statement for a FHIR store</strong>
    </div>
  </div>

  {% if message %}
    <h4> {{ message }} </h4>
  {% endif %}

  <div class="row">
    <div class="col-sm-12">
      <div class="row">
        <div class="col-sm-12">
          <ul class="nav nav-pills" style="margin-bottom: 10px;">
            <meta id="my-data" data-statement="{{requests}}">
            <div style="width: 100%; height: 450px; overflow: scroll;">
              <pre id="data-container"></pre>
            </div>
          </ul>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

consent/templates/consentapproval.html
{% extends 'base.html' %}

{% block consentapproval_active %}active{% endblock %}

{% block body %}

  <div class="page-header">
    <h1>Welcome to Patient Portal</h1>
  </div>

  <div class="row">
    <div class="alert alert-warning" role="alert">
      <strong>Approve the consent for respective role(s).</strong>
      <br><br>This will allow access to -<br><br>
      <ol>
        <li>Medical record numbers</li>
        <li>Medical procedure undergone</li>
        <li>Medical claims history</li>
      </ol>
      <table border="1">
        <thead>
          <tr style="padding: 10px;">
            <th>Role</th>
            <th>Information accessible</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>clinical-admin</td>
            <td>Personal Details, Allergy Intolerance Details, Encounter Details, Observation Details</td>
          </tr>
          <tr>
            <td>internal-researcher</td>
            <td>Personal Details, Allergy Intolerance Details</td>
          </tr>
          <tr>
            <td>external-researcher</td>
            <td>Allergy Intolerance Details, Encounter Details, Observation Details</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  {% if message %}
    <h3> {{ message }} </h3>
  {% endif %}

  <div class="row">
    <div class="col-sm-12">
      <div class="row">
        <div class="col-sm-12">
          <ul class="nav nav-pills" style="margin-bottom: 10px;">
            <li class="active">
              <form action="{% url 'consent:consentapproval'%}" method="post">
                {% csrf_token %}
                <div class="col-sm-12">
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <div class="btn-group" role="group" aria-label="..." id="currentprojectname">
                        <h3 class="panel-title">Summary </h3>
                        <div id='tabledata'>
                          <table id="summarytable" class="table table-bordered">
                            <thead>
                              <tr>
                                <th>Patient ID</th>
                                <th>Requested Role</th>
                                <th>Requested Timestamp</th>
                                <th>Action</th>
                                <th>Status</th>
                              </tr>
                            </thead>
                            <tbody>
                              {% for req in requests %}
                                <tr>
                                  <td>{{ req.patientid }}</td>
                                  <td>{{ req.requestedrole }}</td>
                                  <td>{{ req.timestamp }}</td>
                                  <td>{% if req.status == "Approved" %}
                                    <a class="popup-link" data-url="{% url 'consent:displaydata' req.id %}"><i class="glyphicon glyphicon-eye-open" ></i></a>
                                    {% elif req.status == "Rejected" %}
                                      <button type="submit" value="{{ req.id }}" name="approve" class="btn" style="margin-right: 15px;"> <a>
                                        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span></a>
                                      </button>
                                    {% else %}
                                      <select id="ttl" name="{{ req.id }}_ttl">
                                        <option value="60s">1 Minute</option>
                                        <option value="120s">2 Minutes</option>
                                        <option value="180s">3 Minutes</option>
                                      </select>
                                      <button type="submit" value="{{ req.id }}" name="approve" class="btn" style="margin-right: 15px;"> <a>
                                        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span></a>
                                      </button>
                                      <button type="submit" value="{{ req.id }}" name="reject" class="btn" style="margin-right: 15px;"> <a>
                                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
                                      </button>
                                    {% endif %}</td>
                                  <td>{{ req.status }}</td>
                                </tr>
                              {% endfor %}
                            </tbody>
                          </table>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </form>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

consent/templates/index.html
{% extends 'base.html' %}

{% block body %}

  <script>
    var spinnerCounter = 0;
    setInterval(function() {
        var frames = 19;
        var frameWidth = 30;
        var offset = spinnerCounter * -frameWidth;
        document.getElementById("spinner").style.backgroundPosition = 0 + "px" + " " + offset + "px";
        spinnerCounter++;
        if (spinnerCounter>=frames) spinnerCounter = 0;
    }, 60);

    function revealButton() {
      // Get references to the existing and hidden buttons
      const existingButton = document.getElementById("checkConsent");
      const existingButton2 = document.getElementById("clearConsent");
      const hiddenButton = document.getElementById("requestConsent");
      const hiddenButton2 = document.getElementById("backConsent");
    
      // Hide the existing button
      existingButton.style.display = "none";
      existingButton2.style.display = "none";
    
      // Show the hidden button
      hiddenButton.style.display = "inline";
      hiddenButton2.style.display = "inline";
    }

    var seconds = 0;
    var timer;
    function countDown() {
      if (seconds <= 0) {
        clearInterval(timer);
        document.getElementById("data-container").innerHTML = "<p>The consent approval has expired!<br>Please request for the consent, if required.</p>";
        seconds = 0;
      }

      var minutes = Math.floor(seconds / 60);
      var remainingSeconds = Math.ceil(seconds - minutes * 60);

      // Format the time remaining as mm:ss
      var displayTime = (minutes < 10 ? "0" : "") + minutes + " Minutes  " + (remainingSeconds < 10 ? "0" : "") + remainingSeconds.toString() + " Seconds";

      document.getElementById("counter").innerHTML = displayTime;

      seconds--;
    }
  
    $(function() {
      $('.popup-link').click(function(e) {
        e.preventDefault();
        $('#spinner').show();
        var url = $(this).data('url');
        $.ajax({
          url: url,
          dataType: 'json',
          success: function(resources) {
            if (resources.error == true) {
              alert('Error Occured: ' + resources.message);
            } else {
              const resourceData = resources.data;
              const consentData = resourceData.consent_data;
              const patientData = resourceData.patient_data;
              // console.log(consentData);
              // console.log(patientData);
              clearInterval(timer);
              // Set consent expire timer
              var now = new Date();
              var expireTime = new Date(consentData.expireTime);
              if (now >= expireTime) {
                seconds = 0
              } else {
                seconds = (expireTime.getTime() - now.getTime())/1000
              }
              // Re-enable timer
              timer = setInterval(countDown, 1000);
              // Extract details
              let patientDetails;
              let encounterDetails;
              let observationDetails;
              let intoleranceDetails;
              for (const entry of patientData){
                let resource = entry.resource;
                // console.log(resource);
                // Patient details
                if (resource.resourceType == "Patient") {
                  patientDetails = {
                    'name': resource.name[0].given[0] + ' ' + resource.name[0].family,
                    'gender': resource.gender,
                    'birthDate': resource.birthDate,
                    'lastUpdated': resource.meta.lastUpdated,
                  }
                }
                // Encounter Details
                if (resource.resourceType == "Encounter") {
                  encounterDetails = {
                    'text': resource.reasonCode[0].text,
                    'status': resource.status,
                    'lastUpdated': resource.meta.lastUpdated,
                  }
                }
                // Observation Details
                if (resource.resourceType == "Observation") {
                  observationDetails = {
                    'valueQuantity': resource.valueQuantity.value+ ' ' + resource.valueQuantity.unit,
                    'status': resource.status,
                    'lastUpdated': resource.meta.lastUpdated,
                  }
                }
                // Intolerance Details
                if (resource.resourceType == "AllergyIntolerance") {
                  intoleranceDetails = {
                    'category': resource.category[0],
                    'reaction': resource.reaction[0].manifestation[0].text,
                    'text': resource.code.text,
                    'lastUpdated': resource.meta.lastUpdated,
                  }
                }
              }
              var patientDetailsEl = ''
              if (!!patientDetails) {
                patientDetailsEl += '<tr><td>Patient Name</td><td>' + patientDetails.name + '</td></tr>' +
                '<tr><td>Patient Gender</td><td>' + patientDetails.gender + '</td></tr>' +
                '<tr><td>Patient Birthdate</td><td>' + patientDetails.birthDate + '</td></tr>'
              } 
              var encounterDetailsEl = ''
              if (!!encounterDetails) {
                encounterDetailsEl += '<tr><td>Encounter Detail</td><td>' + encounterDetails.text + '</td></tr>' +
                '<tr><td>Encounter Status</td><td>' + encounterDetails.status + '</td></tr>' +
                '<tr><td>Encounter Last Updated</td><td>' + encounterDetails.lastUpdated + '</td></tr>'
              }
              var observationDetailsEl = ''
              if (!!observationDetails) {
                observationDetailsEl += '<tr><td>Heart Rate</td><td>' + observationDetails.valueQuantity + '</td></tr>' +
                '<tr><td>Observation Status</td><td>' + observationDetails.status + '</td></tr>' +
                '<tr><td>Observation Last Updated</td><td>' + observationDetails.lastUpdated + '</td></tr>'
              }
              var intoleranceDetailsEl = ''
              if (!!intoleranceDetails) {
                intoleranceDetailsEl += '<tr><td>Alergy Intolerance Category</td><td>' + intoleranceDetails.category + '</td></tr>' +
                '<tr><td>Reaction</td><td>' + intoleranceDetails.reaction + '</td></tr>' +
                '<tr><td>Alergant</td><td>' + intoleranceDetails.text + '</td></tr>' +
                '<tr><td>Intolerance Last Updated</td><td>' + intoleranceDetails.lastUpdated + '</td></tr>'
              }

              var html = '<div id="counter-container"><p>Consent is valid for: <span id="counter"> - </span></p></div>' +
                  '<a id="closePopup" class="close">×</a>'+
                  '<div id="data-container"><h2>Data</h2>'+
                    '<table id="summarytable" class="table table-bordered">'+
                      '<tbody>'+
                        patientDetailsEl +
                        encounterDetailsEl +
                        observationDetailsEl +
                        intoleranceDetailsEl +
                      '</tbody>'+
                      '</table>'
              $('.popup').html(html);
              $('.popup').show();
              var close = document.getElementById("closePopup");
              close.onclick = function() {
                $('.popup').hide();
              };
            }
          },
          complete: function(){
            $('#spinner').hide();
          }
        });
      });
    });
  </script>

  <div class="page-header">
    <h1>Welcome to Caregiver Portal</h1>
  </div>

  <div class="row">
    <div class="alert alert-warning" role="alert">
      <strong>Application Requests for Patient Data.</strong>
      <br> <br>
      <table border="1">
        <thead>
          <tr style="padding: 10px;">
            <th>Role</th>
            <th>Information accessible</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>clinical-admin</td>
            <td>Personal Details, Allergy Intolerance Details, Encounter Details, Observation Details</td>
          </tr>
          <tr>
            <td>internal-researcher</td>
            <td>Personal Details, Allergy Intolerance Details</td>
          </tr>
          <tr>
            <td>external-researcher</td>
            <td>Allergy Intolerance Details, Encounter Details, Observation Details</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div id="popup1" class="overlay">
    <div class="popup"></div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <div class="row">
        <div class="col-sm-12">
          <ul class="nav nav-pills" style="margin-bottom: 10px;">
            <li class="active">
                <form id="consentform" action="{% url 'consent:index'%}" method="post">
                    {% csrf_token %}
                    <label for="userid">User ID: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                    <input type="text" id="userid" name="userid" value="{{userid}}"><br><br>
                    <label for="roles">Your Role:</label>&nbsp;&nbsp;&nbsp;&nbsp;
                    <select id="roles" name="roles">
                        <option value="internal-researcher" {% if roles == "internal-researcher" %}selected="selected"{% endif %}>Internal Researcher</option>  
                        <option value="external-researcher" {% if roles == "external-researcher" %}selected="selected"{% endif %}>External Researcher</option>
                        <option value="clinical-admin" {% if roles == "clinical-admin" %}selected="selected"{% endif %}>Clinical Admin</option>
                    </select><br><br>
                    <button type="submit" name="checkConsent" id="checkConsent">Check Consent</button>
                    <button type="submit" name="requestConsent" id="requestConsent" style="display: none;">Request Consent</button>
                    <input type="reset" value="Clear" id="clearConsent" style="display: inline;">
                    <input type="button" value="Back" id="backConsent" onclick="history.back()" style="display: none;">
                </form> 
            </li>
          </ul>
          {% if nomessage %}
            <script>
                revealButton();
            </script>
            <h3> {{ nomessage }} </h3>
          {% elif message %}
            <h3> {{ message }} </h3>
          {% else %}
            <br>
            <div class="col-sm-5">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <div class="btn-group" role="group" aria-label="...">
                    <h3 class="panel-title">Summary</h3> 
                    <div id='tabledata'>
                      <table id="summarytable" class="table table-bordered">
                        <thead>
                          <tr>
                            <th>Patient ID</th>
                            <th>Requested Role</th>
                            <th>Requested Timestamp</th>
                            <th>Action</th>
                            <th>Status</th>
                          </tr>
                        </thead>
                        <tbody>
                          {% for req in requests %}
                          <tr>
                              <td>{{ req.patientid }}</td>
                              <td>{{ req.requestedrole }}</td>
                              <td>{{ req.timestamp }}</td>
                              <td>{% if req.status == "Approved" %}
                                  <a class="popup-link" data-url="{% url 'consent:displaydata' req.id %}"><i class="glyphicon glyphicon-eye-open" ></i></a>
                                  {% else %}
                                  <i class="glyphicon glyphicon-eye-close" ></i>
                                  {% endif %}</td>
                              <td>{{ req.status }}</td>
                          </tr>
                          {% endfor %}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>

  <div style="display: none;" id="spinner"></div>

{% endblock %}

consent/templates/manageresources.html
{% extends 'base.html' %}

{% block body %}

  <nav class="navbar navbar-default">
    <ul class="nav navbar-nav">
      <li><a href="{% url 'consent:index'%}">Home</a></li>
      <li><a href="{% url 'consent:consentapproval'%}">Consent Approval</a></li>
      <li class="active"><a href="{% url 'consent:manageresources'%}">Manage Resources</a></li>
      <li><a href="{% url 'consent:capabilitystatement'%}">Capability Statement</a></li>
    </ul>
  </nav>

  <div class="page-header">
    <h1>Welcome to Resource Manager Portal</h1>
  </div>

  <div class="row">
    <div class="alert alert-warning" role="alert">
      <strong>Upload resources that conform with the profile(s) in the implementation guide.</strong>
      <br><br>This portal will not allow to upload resources that don't conform to the profile(s) in the implementation guide. Refer below table for the valid structure definition(s).<br><br>
      <table border="1">
        <thead>
          <tr style="padding: 10px;">
            <th>Resource Type</th>
            <th>Structure Definition</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Patient</td>
            <td>http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient|5.0.1</td>
          </tr>
          <tr>
            <td>...</td>
            <td>...</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  {% if message %}
    <h4> {{ message }} </h4>
  {% endif %}

  <div class="row">
    <div class="col-sm-12">
      <div class="row">
        <div class="col-sm-12">
          <ul class="nav nav-pills" style="margin-bottom: 10px;">
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <label for="json_file">Choose a JSON file to upload:</label>
              <input type="file" name="json_file" id="json_file">
              <br><br>
              <input type="submit" value="Upload">
            </form>
          </ul>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>{% block title %}Consent & Conformance POC{% endblock %}</title>
  {% load static %}
  <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" type="text/css" href="{% static 'cmapi/style.css' %}" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

  <link rel="stylesheet" type="text/css" href="{% static 'cmapi/bootstrap-theme.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'cmapi/bootstrap.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'cmapi/ie10-viewport-bug-workaround.css' %}" />
</head>

<body>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
          aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Consent & Conformance POC</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'consent:index'%}">Consent & Conformance POC</a>
        <ul class="nav navbar-nav">
          <!-- <li class="active"><a href="{% url 'consent:index'%}">Home</a></li> -->
          <li class="{% block consentapproval_active %}{% endblock %}"><a href="{% url 'consent:consentapproval'%}">Consent Approval</a></li>
          <li class="{% block manageresources_active %}{% endblock %}"><a href="{% url 'conformance:manageresources'%}">Manage Resources</a></li>
          <li class="{% block capabilitystatement_active %}{% endblock %}"><a href="{% url 'conformance:capabilitystatement'%}">Capability Statement</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container-fluid " role="main">
    {% block body %}
    {% endblock %}
  </div>
</body>

</html>